numero1 = int(input("Anna ensimmäinen kokonaisluku: "))
numero2 = int(input("Anna toinen kokonaisluku: "))
print("Numeroiden summa on:" )
print(numero1 + numero2)
print("Numeroiden tulo on:" )
print(numero1 * numero2)
print("Numeroiden keskiarvo on: ")
print((numero1 + numero2) / 2)